### ISSUE TITLE
api package name change

### ISSUE THREAD

**Issue by fm-tibco** [project-flogo/rules#17]
**Current behavior:**

api package name is "ruleapi" which in an import looks redundant: github.com/project-flogo/rules/ruleapi

**Expected behavior:**

I think "github.com/project-flogo/rules/api" would look cleaner

**What is the motivation / use case for changing the behavior?**

**Additional information you deem important (e.g. I need this tomorrow):**

**Comment by balamg** [comment]
The code may look a bit odd like api.NewRule "ruleapi." makes is clearer, though there is stutter in the import statement

**Comment by mellistibco** [comment]
You can always alias the import to ruleapi if you think it makes the code looker cleaner:

```golang
import (
...
ruleapi "github.com/project-flogo/rules/api"
)
```

I think its important to have a clean import path.

**Comment by vpatil-tibco** [comment]
The end user facing api looks better off with ruleapi than simply api. Yes, an alias can work here. But then it becomes optional for end user to use an alias.

Another cleanup candidate is ruleaction for a flogo action can simply be action.

**Comment by mellistibco** [comment]
@vpatil-tibco I'm not sire I agree with you. rules/ruleapi is a bit redundant, obviously its an api for rules when its nested under that package. Perhaps calling it something different, all together? Secondly, an alias being optional is fine, the dev can alias it to whatever makes sense for them.

**Comment by vpatil-tibco** [comment]
@mellistibco I agree to the base issue logged by @fm-tibco 
But from an oob usage perspective, i feel ruleapi.NewRule looks cleaner than api.NewRule. Also my take on this comes from the fact that i haven't encountered an user facing api package, there might be just that i haven't come across one. 
So really 2 options, if we are all ok with api then use that else find a better package name.

**Comment by balamg** [comment]
Closing this - lets keep it as ruleapi itself
