### ISSUE TITLE
Expression syntax for conditions

### ISSUE THREAD

**Issue by balamg** [project-flogo/rules#23]
**Current behavior:**
Currently, one has to write code in Go for authoring rule conditions

**Expected behavior:**

**What is the motivation / use case for changing the behavior?**
For ease of use, it would be nice to support an expression syntax for conditions. For example,
rule.AddCondition ("$customer.name == Bob")

**Additional information you deem important (e.g. I need this tomorrow):**

**Comment by mellistibco** [comment]
We should use the expression syntax exposed by Flogo Core.
