### ISSUE TITLE
Update the README to reflect both usage in the context of a Flogo app & the API

### ISSUE THREAD

**Issue by mellistibco** [project-flogo/rules#30]
**Current behavior (how does the issue manifest):**
The current README only reflects getting started and usage via the API.

**Expected behavior:**
The README should capture all variants of usage, such as, within the context of a Flogo application leveraging the JSON DSL. We should also capture the usage around leveraging the streaming action along side the rules action in a single application.

**Comment by balamg** [comment]
PR #41
