### ISSUE TITLE
Migrate to `project-flogo/core`

### ISSUE THREAD

**Issue by mellistibco** [project-flogo/rules#34]
**Current behavior (how does the issue manifest):**
Currently `TIBCOSoftware/flogo-lib` is used.

**Expected behavior:**
Migrate to `project-flogo/core`.

**Comment by balamg** [comment]
@mellistibco What is the corresponding location of `github.com/TIBCOSoftware/flogo-contrib/action/flow@master`

**Comment by balamg** [comment]
See PR #35 for details

**Comment by balamg** [comment]
Closing, as per PR #40
