### ISSUE TITLE
A tuple remains in the rule session's network after retract is invoked

### ISSUE THREAD

**Issue by jpark800** [project-flogo/rules#47]
**Current behavior (how does the issue manifest):**
After retracting a tuple, asserting another tuple with the same key in the same rule session fails as the tuple is found when looked up.

**Expected behavior:**
The retract should take the tuple out of play for the rule session but it doesn't.

**Minimal steps to reproduce the problem (not required if feature enhancement):**
Described in the current behavior above.

**Additional information you deem important (e.g. issue happens only occasionally):**
The purpose of Retract api compared to the Delete api in the rule session api is not clearly described.

**Comment by balamg** [comment]
Fixed with PR #48
