### ISSUE TITLE
Tool to generate functions.go based on rules descriptor

### ISSUE THREAD

**Issue by rameshpolishetti** [project-flogo/rules#58]
**Current behavior:**
User has to write down functions.go with `condition evaluators` and `action functions` as defined in the rules descriptor json.

**Expected behavior:**
Add a `cli tool` or `flogo cli plugin` to generate functions.go boilerplate code based on supplied rules descriptor json.

**What is the motivation / use case for changing the behavior?**

- Improves turn around time to create and run a new rule application.
- Eliminates human errors caused due to mismatch function names (usually spelling mistakes)  between descriptor json and functions.go

**Additional information you deem important (e.g. I need this tomorrow):**

**Comment by tibmatt** [comment]
Hmmm - I guess? Honestly I'd prefer this to be done:
1. Conditions utilize the flogo expression language with bindings to the Tuple store
2. Action functions - same thing (or wrap it in an activity if used within a flogo flow)

Doing a code generator isn't really moving the needle.

**Comment by balamg** [comment]
I think all this is asking is for stubs to be generated and save some typing/and errors. (unlike the elaborate codegen in BE) So it would be a good little nifty utility to have.. #2 that Matt mentioned above would be really cool.. When a rule fires, execute a Flogo-flow.. That would be a nice ER. And of course #1 above, which was done but broke when Flogo-core changed their APIs. That needs to be redone.

**Comment by rameshpolishetti** [comment]
I echo @balamg, points 1 & 2 mentioned by @tibmatt are really cool !!
Not sure about the complexity involved in point 1 & 2 realization, until then this kind of tool saves some time/errors.

**Comment by rameshpolishetti** [comment]
Closing this issue as this kind of tool may not be required as issues #22 & #69 effectively handles the problem statement.
