### ISSUE TITLE
Add Kafka trigger example

### ISSUE THREAD

**Issue by rameshpolishetti** [project-flogo/rules#65]
**Current behavior:**
Currently, we have only `rest` trigger based examples

**Expected behavior:**
Add `kafka` trigger based example, describing how a Kafka message can be input source to `rule` action & how kafka topic and messages are mapped to `tuple` type and data.

**Comment by mellistibco** [comment]
I don't understand this enhancement request. Flogo Rules should support any Flogo trigger. Why are we suggesting to implement the exact the same thing implemented already in flogo core?

**Comment by rameshpolishetti** [comment]
@mellistibco It's my bad. I didn't mean to add same Kafka trigger here instead add an example for kafka channel and update rules/action input parameters (for mapping, only if required). Let me update the issue title/description accordingly.

**Comment by mellistibco** [comment]
i think we need to clean up terminology also. we need to keep things consistent. A `channel` is basically the same thing as a trigger, can we work on cleaning up terminology both in code and in documentation? I can't think of any reason to have multiple overlapping terms. Flogo has standardized on `triggers` and we should stick with that as a way to define/describe an input source into an action.

**Comment by rameshpolishetti** [comment]
@mellistibco agreed, updating the issue terminology accordingly.
Don't want to dilute the original objective of this issue. Can we take up fixing any terminology deviations as a different issue?

**Comment by mellistibco** [comment]
@rameshpolishetti yes, let's create a different issue to capture and track the larger task of fixing terminology, etc.
