### ISSUE TITLE
TrackNtrace in develop branch: Package in sitting is not changed to delayed state even if the package is idle for 10 seconds

### ISSUE THREAD

**Issue by ykalidin** [project-flogo/rules#91]
**Current behavior (how does the issue manifest):**
Trackntrace example in develop branch:
When a package is in sitting state for 10 seconds it should automatically be changed to delayed state. The state of the package is not changing. 

**Minimal steps to reproduce the problem (not required if feature enhancement):**
Run the example in the [readme](https://github.com/project-flogo/rules/blob/develop/examples/flogo/trackntrace/README.md) .
Run the below command :
curl http://localhost:7777/moveevent?packageid=PACKAGE1\&targetstate=sitting

The package stays in sitting state even after 10 seconds.

**Comment by nareshkumarthota** [comment]
fix is merged into develop by PR #92
